 version: "3"

 
 openstreetmap:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: "osm-preprocessors:latest"
        labels:
            ca.mcgill.a11y.image.preprocessor: 3
            ca.mcgill.a11y.image.port: 8080